apiVersion: v1
kind: Service
metadata:
  name: etlflow-test
  namespace: dev
spec:
  selector:
    app: etlflow-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: debug
    - protocol: TCP
      port: 9010
      targetPort: 9010
      name: monitor
  type: NodePort