addSbtPlugin("com.eed3si9n"     % "sbt-assembly"          % "0.15.0")
addSbtPlugin("io.crashbox"      % "sbt-gpg"               % "0.2.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"         % "1.9.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.6.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-version-policy"    % "2.0.1")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"       % "2.4.18")
addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.4.6")
