addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
addSbtPlugin("io.crashbox" % "sbt-gpg" % "0.2.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "1.1.0")
addSbtPlugin("com.github.xuwei-k" % "sbt-class-diagram" % "0.2.1")