{
 "title": "JVM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GC seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"http4s\"}[2m])",
     "legendFormat": "{{gc}} ({{job}})"
    }
   ]
  },
  {
   "title": "Memory Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"http4s\"}",
     "legendFormat": "{{pool}} ({{job}})"
    }
   ]
  },
  {
   "title": "VM threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"http4s\"}",
     "legendFormat": "Current ({{job}})"
    },
    {
     "expr": "jvm_threads_peak{job=\"http4s\"}",
     "legendFormat": "Peak ({{job}})"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{job=\"http4s\"}",
     "legendFormat": "Max ({{job}})"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"http4s\"}",
     "legendFormat": "Used ({{job}})"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"http4s\"}",
     "legendFormat": "Commited ({{job}})"
    }
   ]
  }
 ]
}