version: '3.4'
services:
  postgres:
    image: 'postgres:13-alpine'
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
    - POSTGRES_USER=etlflow
    - POSTGRES_PASSWORD=etlflow
    - POSTGRES_DB=etlflow
    ports:
    - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=etlflow@etlflow.com
      - PGADMIN_DEFAULT_PASSWORD=etlflow
    ports:
      - '5050:80'
  webserver:
    image: 'etlflow-server:0.12.0'
#    entrypoint: /opt/docker/bin/exampleserver
    command: run_server
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    depends_on:
     - postgres
    environment:
        LOG_DB_URL: 'jdbc:postgresql://postgres:5432/etlflow'
        LOG_DB_USER: etlflow
        LOG_DB_PWD: etlflow
        LOG_DB_DRIVER: org.postgresql.Driver
    ports:
    - '8080:8080'

