name:  Publish Docs
on:
  push:
    branches:
      - gh-pages
jobs:
  generatedocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Dependencies
        run: >
          gem install jekyll:4.0.0
      - name: Compile Docs
        run: sbt ";project docs; makeMicrosite;"
      - name: Remove site folder from root
        uses: JesseTG/rm@v1.0.2
        with:
          path: /home/runner/work/etlflow/etlflow/site/
      - name: Copy Site Folder
        run: |
          cp -r /home/runner/work/etlflow/etlflow/modules/docs/target/site  /home/runner/work/etlflow/etlflow/site/
      - name: Commit Docs
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git add /home/runner/work/etlflow/etlflow/site/
          git commit -am "Automated report"
          git push
