name: Http Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 14 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Http Tests For 2.12
        run: sbt ";project http; ++2.12.15 test"
      - name: Run Http Tests For 2.13
        run: sbt ";project http;  ++2.13.7 test"
      - name: Run Http Tests For All Modules
        run: sbt ";project http; +test"