name: Scala Coding Style Check
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check scalastyle on etlflow
        run: sbt "project etlflow; Test/scalastyle"
      - name: Check scalastyle on examples
        run: sbt "project examples; Test/scalastyle"
