name: Scala Code Linting Check
on: [push]
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'sbt'
      - name: Check scalafmt on etlflow
        run: sbt "project etlflow; scalafmtCheckAll"
  scalastyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'sbt'
      - name: Check scalastyle on etlflow
        run: sbt "project etlflow; scalastyle; Test/scalastyle"
      - name: Check scalastyle on examples
        run: sbt "project examples; scalastyle; Test/scalastyle"
