name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: etlflow
          POSTGRES_USER: etlflow
          POSTGRES_DB: etlflow
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Core Tests
      run: sbt ";project core; test:runMain etlflow.LoadData run_db_migration; test;"
      env:
        LOG_DB_URL: jdbc:postgresql://localhost:5432/etlflow
        LOG_DB_USER: etlflow
        LOG_DB_PWD: etlflow
        LOG_DB_DRIVER: org.postgresql.Driver
    - name: Run Scheduler Tests
      run: sbt ";publishLocal; project examples; docker:stage;  project scheduler; testOnly etlflow.webserver.*; testOnly etlflow.executor.LocalExecutorTestSuite; testOnly etlflow.executor.LocalSubProcessExecutorTestSuite;"
      env:
        LOG_DB_URL: jdbc:postgresql://localhost:5432/etlflow
        LOG_DB_USER: etlflow
        LOG_DB_PWD: etlflow
        LOG_DB_DRIVER: org.postgresql.Driver
