name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt ";project core; testOnly etlflow.utils.*; testOnly etlflow.steps.spark.*; testOnly etlflow.steps.db.*; testOnly etlflow.log.*; testOnly etlflow.TransformationTestSuite;"
