name: Scala Dependency Updates Check
on: [push]
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'sbt'
      - name: Check Dependency Updates for core
        run: sbt core/dependencyUpdates
      - name: Check Dependency Updates for jdbc
        run: sbt jdbc/dependencyUpdates
      - name: Check Dependency Updates for email
        run: sbt email/dependencyUpdates
      - name: Check Dependency Updates for gcp
        run: sbt gcp/dependencyUpdates
      - name: Check Dependency Updates for http
        run: sbt http/dependencyUpdates
      - name: Check Dependency Updates for k8s
        run: sbt k8s/dependencyUpdates
      - name: Check Dependency Updates for redis
        run: sbt redis/dependencyUpdates
      - name: Check Dependency Updates for spark
        run: sbt spark/dependencyUpdates
